<a href="https://colab.research.google.com/github/Mahnoorlaghariii/DSA20SW059-lab4/blob/main/20sw059.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [2]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array.
Y = X[X % 2 != 0]

print("Original Array X:")
print(X)

print("\nOdd Numbers in Array X:")
print(Y)


Original Array X:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd Numbers in Array X:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [4]:
import numpy as np

# Create a 4 x 4 ndarray with columns of consecutive numbers using broadcasting.
X = np.arange(1, 5)[:, np.newaxis] * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


# New Section

In [5]:
#task-4
from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.19571831  0.30516558  1.61690529 ...  0.9161687  -0.82546884
   0.35972101]
 [-1.25538037  1.68200191  0.60514671 ...  0.26613961  0.41736487
  -1.01404184]
 [-1.14771435  1.43455206  0.19281803 ...  0.85062523 -1.13882384
   1.48018553]
 ...
 [-0.92209573  0.42783303  0.51124309 ...  0.72291681  0.44630081
  -0.49706408]
 [ 1.29294416 -1.25708188  1.17986512 ... -0.52916625 -0.51987713
   0.09188916]
 [ 0.12576215 -1.4192285   0.09962045 ...  0.06613066 -0.80006167
   0.63239737]]
Average of all values in X_norm: -2.9842794901924206e-17
Average of minimum values in each column of X_norm: -1.7307039469474415
Average of maximum values in each column of X_norm: 1.7190376151213933
Random permutation of row indices: [911 972 203 289 765 600 521 710  18 645 498 852 413 173 683 209 277 325
 572 735 356 436 931 877 905 473 826  15  96 347 480 526 129 204 912 869
 977 902  34 256 973 31